FROM rocker/tidyverse:latest

## Adapted from https://hub.docker.com/r/asachet/rocker-stan/dockerfile
## To strip down the rocker version
## and also write the install_rstan.R file inside of docker instead of
## copying it locally
RUN apt-get update \
	&& apt-get install -y --no-install-recommends \
	clang

RUN apt-get install -y --no-install-recommends gfortran-7


## From https://github.com/stan-dev/rstan/wiki/Installing-RStan-on-Linux
RUN echo \
	'dotR <- file.path(Sys.getenv("HOME"), ".R")\n\
	if (!file.exists(dotR)) dir.create(dotR)\n\
	M <- file.path(dotR, "Makevars")\n\
	if (!file.exists(M)) file.create(M)\n\
	cat("\nCXX14FLAGS=-O3 -march=native -mtune=native -fPIC",\n\
	"CXX14=g++",\n\
	file = M, sep = "\n", append = TRUE)'\
	| cat >> install_rstan.R

RUN ["r", "install_rstan.R"]


# Install rstan
RUN install2.r --error --deps TRUE \
    rstan \
    && rm -rf /tmp/downloaded_packages/ /tmp/*.rds

# Installing the rest 
RUN install2.r -s --error \
	bayesplot \
	brms \
	coda \
	loo \
	projpred \
	rstanarm \
	rstantools \ 
	shinystan \
	tidybayes \
	igraph \
	ggthemes

RUN R -e "update.packages(repos = 'http://cran.us.r-project.org')"

RUN chown -R rstudio:rstudio /usr/local/lib/R/
